channels:
  - etetoolkit
  - conda-forge
  - bioconda

dependencies:
  - pandas
  - matplotlib
  - bioconda::biopython
  - bioconda::spades
  - bioconda::prokka
  - etetoolkit::ete3
  - bioconda::clustalo
  - bioconda::fasttree
