name: bt2100

channels:
  - bioconda  # required for biopython
  - conda-forge # required for pyvis

dependencies:
  - jupyterlab
  - matplotlib
  - pandas
  - biopython
  - seaborn
  - statsmodels
  - pyvis


# if not using conda-forge  
#  - pip
#  - pip:
#    - pyvis  #also availabe in conda-forge