name: bt2100

channels:
  - bioconda    # required for biopython, goatools
  - conda-forge # required for pyvis

dependencies:
  - jupyterlab   # lectures: all
  - matplotlib   # lectures:
  - pandas       # lectures:
  - biopython    # lectures:
  - seaborn      # lectures:
  - statsmodels  # lectures: 14
  - pyvis        # lectures: 9, 14
  - goatools     # lectures: 7


# alternatively availabe in pip: 
#  - pip
#  - pip:
#    - pyvis
#    - goatools