name: bt2100

channels:
  - bioconda    # required for biopython, pyrodigal, goatools
  - conda-forge # required for pyvis

dependencies:
  - jupyterlab   # lectures: all
  - matplotlib   # lectures: 2
  - biopython    # lectures: 2, 3, 4
  - pyrodigal    # lectures: 3
  - goatools     # lectures: 7
  - pyvis        # lectures: 9, 14
  - statsmodels  # lectures: 14
  - pandas       # lectures:
  - seaborn      # lectures:


# alternatively availabe in pip: 
#  - pip
#  - pip:
#    - pyvis
#    - goatools